### ISSUE TITLE
Solicitud para ser agregada como colaboradora

### ISSUE THREAD

**Issue by nayruthCalla** [makeitrealcamp/interview-questions#6]
Hola, soy **Nayruth Calla**, mentora de apoyo en el bootcamp del programa **top-fs-proinnóvate-1 - 2024**. Recientemente he estado guiando a los estudiantes en entrevistas técnicas, y he preparado un conjunto actualizado de preguntas que considero muy útiles para su desarrollo.

Me gustaría actualizar este repositorio con las nuevas preguntas de entrevista técnica y respuestas, para después compartirlo con los estudiantes de mi grupo, para que puedan acceder y practicar.

¿Podrían agregarme como colaboradora para que pueda hacer estas actualizaciones al repositorio? , quedo atenta!

¡Gracias por su tiempo y consideración! 🙏✨

**Comment by anayib** [comment]
Added
